name: darklight
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - opencv=4.4.0.42
  - pip=21.0.1
  - python=3.8
  - pytorch=1.8.1
  - torchvision=0.8.2
  - pip:
    - tensorboardx==2.3.0